### ISSUE TITLE
Adding a resource to accepted topics causes exception in backend

### ISSUE THREAD

**Issue by jsobbe** [Humorloos/semantic_web_project#38]
Possible since #36 

`Exception in thread "JavaFX Application Thread" java.util.NoSuchElementException: QueryIteratorCloseable`

`at backend.TopicManagerImpl.getSuggestionsForCurrentTopic(TopicManagerImpl.java:110)
	at ui.controller.ProposedTopicListEntry.lambda$0(ProposedTopicListEntry.java:70)
	`

Does not seem to occur for every single topic? Reproducable with 'Mannheim' -> '2000 UEFA European Under-18 Championship'

**Comment by jsobbe** [comment]
Need to check if this is still an issue. Currently cannot reproduce it anymore. Possibly fixed by some changes in the backend?
